# Generated by Django 4.2.11 on 2024-04-09 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='item_type',
        ),
    ]
